version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      args: 
        MONGO_URI:  mongodb://mongo:27017/jeux?directConnection=true&serverSelectionTimeoutMS=2000&appName=mongosh+2.1.3

    container_name: backend
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://57.18.238.136:5000
    container_name: frontend
    restart: always
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - app-network
volumes:
  mongo_data:

networks:
  app-network:
  # nginx-proxy-manager_default:
  #   external: true
