version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - 5000:5000
    environment:
      - MONGODB_URI=mongodb://mongo:27017/games
    depends_on:
      - mongo
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    environment:
      - REACT_APP_API_URL=http://macollectionjv.duckdns.org:5000
    ports:
      - 8080:80
    depends_on:
      - backend
    networks:
      - app-network
volumes:
  mongo_data:

networks:
  app-network:
  # nginx-proxy-manager_default:
  #   external: true
